# Numpy

file made with Yeongho Lee, UNIST

- **Numpy** is the basic package for data analysis with Python, specialized for computation of arrays.   
This package is also the basis of other popular packages including **Pandas**.



### Import Numpy



In [1]:
import numpy as np

### Basics

- Vectors

In [2]:
a = [1,2,3] # list
b = np.array([1,2,3]) #ndarry

print(a)
print(b)

[1, 2, 3]
[1 2 3]


In [3]:
np.array(a)

array([1, 2, 3])

In [4]:
b

array([1, 2, 3])

In [5]:
print(b.shape)

(3,)


In [6]:
print([1,2,3]+[4,5,6]) #list
print(np.array([1,2,3])+np.array([4,5,6])) #ndarry

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [7]:
#indexing

print(b[0])
print(b[0:2])

1
[1 2]


In [8]:
# elementwise operation

b+b

array([2, 4, 6])

In [9]:
b*b

array([1, 4, 9])

In [10]:
b/b

array([1., 1., 1.])

In [11]:
2 * b

array([2, 4, 6])

In [12]:
b/5

array([0.2, 0.4, 0.6])

- Matrices

In [13]:
mat=np.array([[2,5,18,14,4], [12,15,1,2,8]])
print(mat.shape)
mat

(2, 5)


array([[ 2,  5, 18, 14,  4],
       [12, 15,  1,  2,  8]])

In [14]:
#indexing

print(mat[1,2])
print(mat[1][2])

1
1


In [15]:
print(mat[0,:])

[ 2  5 18 14  4]


In [16]:
print(mat[:,0])

[ 2 12]


In [17]:
print(mat[1,2:4])

[1 2]


In [18]:
print(mat[:,2:4])

[[18 14]
 [ 1  2]]


※ Numpy arrays are not restricted to 2-dimensional arrays.
We can construct n-dimensional arrays for any n:




In [19]:
mat2=np.array([[[2,5,18,14,4], [12,15,1,2,8]],[[3,5,8,12,7], [11,1,0,20,8]]])

In [20]:
print(mat2.shape)
print(mat2[0,1,2])
print(mat2[0][1][2])

(2, 2, 5)
1
1


In [21]:
x = np.random.rand(5,5)
print(x)
#each element is sampled from the uniform distribution [0,1)

[[0.15614459 0.58812502 0.19914273 0.09825757 0.70853046]
 [0.85940256 0.02252427 0.09842259 0.08127294 0.93250646]
 [0.47959341 0.39325502 0.37254829 0.67574429 0.41845539]
 [0.18176645 0.66103953 0.39940447 0.20404219 0.73633889]
 [0.37346429 0.36897047 0.57414548 0.68266417 0.22934009]]


In [22]:
x = np.random.randint(100,size=(2,3))
print(x)


[[50 58 62]
 [85 73 19]]


In [23]:
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
x = np.ones((4,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
x = np.eye(4) #identity matrix
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
x = np.identity(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
#Be carefull!!!

Mat=np.array([[1,2,3],[4,5,6]])
B=Mat[:2,:2]
print(B)
B[0,0]=0
print(B)
print(Mat)

[[1 2]
 [4 5]]
[[0 2]
 [4 5]]
[[0 2 3]
 [4 5 6]]


- To avoid the above problem, use `numpy.copy()` function:

In [28]:
Mat=np.array([[1,2,3],[4,5,6]])
B=np.copy(Mat[:2,:2])
print(B)
B[0,0]=0
print(B)
print(Mat)

[[1 2]
 [4 5]]
[[0 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [29]:
x = np.random.rand(4,3)
print(x)

[[0.52894827 0.35178377 0.79467525]
 [0.04231291 0.7926754  0.78740306]
 [0.85612305 0.19971513 0.12682472]
 [0.84344875 0.45848726 0.51422774]]


In [30]:
x[1,2] = -5
print(x)

[[ 0.52894827  0.35178377  0.79467525]
 [ 0.04231291  0.7926754  -5.        ]
 [ 0.85612305  0.19971513  0.12682472]
 [ 0.84344875  0.45848726  0.51422774]]


In [31]:
x[0:2,:] += 1
print(x)

[[ 1.52894827  1.35178377  1.79467525]
 [ 1.04231291  1.7926754  -4.        ]
 [ 0.85612305  0.19971513  0.12682472]
 [ 0.84344875  0.45848726  0.51422774]]


In [32]:
x[2:4,1:3] = 0.5
print(x)

[[ 1.52894827  1.35178377  1.79467525]
 [ 1.04231291  1.7926754  -4.        ]
 [ 0.85612305  0.5         0.5       ]
 [ 0.84344875  0.5         0.5       ]]


In [33]:
x[x>0.5] = 0
print(x)

[[ 0.   0.   0. ]
 [ 0.   0.  -4. ]
 [ 0.   0.5  0.5]
 [ 0.   0.5  0.5]]


In [34]:
x

array([[ 0. ,  0. ,  0. ],
       [ 0. ,  0. , -4. ],
       [ 0. ,  0.5,  0.5],
       [ 0. ,  0.5,  0.5]])

In [35]:
x>0.1

array([[False, False, False],
       [False, False, False],
       [False,  True,  True],
       [False,  True,  True]])

In [36]:
print(2*x+1)

[[ 1.  1.  1.]
 [ 1.  1. -7.]
 [ 1.  2.  2.]
 [ 1.  2.  2.]]


### Matrix multiplication

In [37]:
A=np.random.rand(4,3)

In [38]:
B=np.random.rand(3,3)

In [39]:
A.dot(B)

array([[0.896762  , 1.05287981, 1.19425104],
       [1.2538545 , 1.21955877, 1.62201479],
       [1.06939405, 0.8835199 , 1.39693841],
       [0.63953355, 0.45764204, 0.90324012]])

In [40]:
np.dot(A,B)

array([[0.896762  , 1.05287981, 1.19425104],
       [1.2538545 , 1.21955877, 1.62201479],
       [1.06939405, 0.8835199 , 1.39693841],
       [0.63953355, 0.45764204, 0.90324012]])

In [41]:
B.dot(A)

ValueError: ignored

Note !!

In [42]:
A

array([[0.57538847, 0.17782443, 0.79461167],
       [0.96195153, 0.62655392, 0.69367228],
       [0.84760976, 0.85922712, 0.35727791],
       [0.41848917, 0.78988357, 0.14278045]])

In [43]:
A.shape

(4, 3)

In [44]:
y = np.array([1,0,0]) # 3 * 1
print(A.dot(y))

[0.57538847 0.96195153 0.84760976 0.41848917]


In [45]:
y = np.array([1,0,1,0]) #  1 * 4
print(y.dot(A))

[1.42299822 1.03705155 1.15188958]


In [46]:
y.shape

(4,)

https://stats.stackexchange.com/questions/284995/are-1-dimensional-numpy-arrays-equivalent-to-vectors

$\rightarrow$ Python automatically transposes the one-dimensional array with shape (n,) in a way that matrix multiplication can be conducted.

$\rightarrow$ Only for vectors with shape (n,), not vectors with shape (n,1) or (1,n).

In [47]:
y=np.array([[1],[0],[1],[0]])

In [48]:
y

array([[1],
       [0],
       [1],
       [0]])

In [49]:
y.shape

(4, 1)

In [50]:
#you can do also
y = np.array([1,0,1,0]).reshape((4,1))

In [51]:
y

array([[1],
       [0],
       [1],
       [0]])

In [52]:
print(y.dot(A)) # 4 * 1   4 * 3

ValueError: ignored

### Transpose

In [53]:
print(y.T.dot(A))

[[1.42299822 1.03705155 1.15188958]]


$$
A_{ij}^T = A_{ji}
$$

In [54]:
A.T

array([[0.57538847, 0.96195153, 0.84760976, 0.41848917],
       [0.17782443, 0.62655392, 0.85922712, 0.78988357],
       [0.79461167, 0.69367228, 0.35727791, 0.14278045]])

In [55]:
A

array([[0.57538847, 0.17782443, 0.79461167],
       [0.96195153, 0.62655392, 0.69367228],
       [0.84760976, 0.85922712, 0.35727791],
       [0.41848917, 0.78988357, 0.14278045]])

### inner products and outer products of vectors

In [56]:
#inner products

y = np.array([2,-1,3])
z = np.array([-1,2,2])
print(np.dot(y,z)) # y.dot(z)
print(np.dot(z,y))

2
2


In [57]:
#outer products yz^T

print(np.outer(y,z))

[[-2  4  4]
 [ 1 -2 -2]
 [-3  6  6]]


inner product : (1,3) * (3, 1) ====> (1,1)
\
outer product : (3,1) * (1,3)  ====> (3,3)

### Inverse

In [58]:
x=np.random.rand(4,4)
y=np.linalg.inv(x)
print(x)
print(y)
print(x.dot(y))

[[2.56250016e-01 1.91384802e-02 2.43463485e-01 1.26317011e-01]
 [2.56680415e-01 9.04914936e-01 4.87956702e-01 8.60171095e-01]
 [5.56634306e-04 8.86313636e-01 7.72209709e-01 1.24622939e-01]
 [9.38817727e-02 4.46751864e-01 5.84512695e-01 6.32633301e-02]]
[[ 12.43994533  -2.08752858  10.76407312 -17.65944648]
 [  6.12786994  -1.2172576    9.01901116 -13.4513957 ]
 [ -5.94731273   0.9948938   -7.72176585  13.55883459]
 [ -6.78499928   2.50168507  -8.31982998  11.7291534 ]]
[[ 1.00000000e+00 -4.93762769e-16  1.81500446e-15 -4.91581280e-15]
 [ 6.78847502e-16  1.00000000e+00  2.17098576e-15 -1.08301131e-15]
 [ 2.89148649e-17  2.25663507e-16  1.00000000e+00 -1.53668028e-16]
 [ 3.47549637e-16  4.86827497e-18  1.60095514e-16  1.00000000e+00]]


In [59]:
#applied elementwise

np.round(x.dot(y),3)

array([[ 1., -0.,  0., -0.],
       [ 0.,  1.,  0., -0.],
       [ 0.,  0.,  1., -0.],
       [ 0.,  0.,  0.,  1.]])

In [60]:
np.round(3.5678,3)

3.568

In [61]:
print(x)

[[2.56250016e-01 1.91384802e-02 2.43463485e-01 1.26317011e-01]
 [2.56680415e-01 9.04914936e-01 4.87956702e-01 8.60171095e-01]
 [5.56634306e-04 8.86313636e-01 7.72209709e-01 1.24622939e-01]
 [9.38817727e-02 4.46751864e-01 5.84512695e-01 6.32633301e-02]]


In [62]:
np.sqrt(np.abs(x))

array([[0.50621143, 0.1383419 , 0.49342019, 0.35541104],
       [0.50663637, 0.95127017, 0.69853898, 0.92745409],
       [0.0235931 , 0.94144232, 0.87875464, 0.35301974],
       [0.30640133, 0.66839499, 0.7645343 , 0.25152203]])

## Mean, Var, Std, Median, Sum, Cov

In [63]:
x = np.random.rand(5,3)
x

array([[0.13526279, 0.28318842, 0.97614298],
       [0.01948953, 0.16824088, 0.73441519],
       [0.38178157, 0.31230602, 0.48384401],
       [0.94146461, 0.56797154, 0.69145852],
       [0.36541321, 0.91759949, 0.11666415]])

### np.mean()


In [64]:
print("Mean:", np.mean(x))
print("Mean along rows :", np.mean(x, axis=0)) #np.mean(x, 0)
print("Mean along columns :", np.mean(x, axis=1)) # np.mean(x,1)

Mean: 0.47301619347878976
Mean along rows : [0.36868234 0.44986127 0.60050497]
Mean along columns : [0.46486473 0.30738187 0.39264387 0.73363156 0.46655895]


### np.var()


- Sample Variance
$$
S^2 = {1\over N-1} \sum^n_{i=1}{(X_i - \bar X)}^2
$$
- `numpy.var()` however uses $N$ instead of $N-1$ in the denominator (It calculates the population variance instead of sample variance.)

In [65]:
print("Variance:", np.var(x))
print("Variance along rows :", np.var(x, axis=0)) #np.var(x,0)
print("Variance along columns :", np.var(x, axis=1)) #np.var(x,1)

Variance: 0.09445454046847615
Variance along rows : [0.10093642 0.07174808 0.08300403]
Variance along columns : [0.13434972 0.09486656 0.00496321 0.0241388  0.11203147]


### np.std()



In [66]:
print("Standard Deviation :", np.std(x))
print("Standard Deviation along rows  :", np.std(x, axis=0)) #np.std(x,0)
print("Standard Deviation along columns :", np.std(x, axis=1)) #np.std(x,1)

Standard Deviation : 0.3073345741508367
Standard Deviation along rows  : [0.31770493 0.26785833 0.28810419]
Standard Deviation along columns : [0.36653748 0.30800415 0.07045005 0.15536665 0.33471102]


### np.median()


- When $n$ is odd.
\
\
    np.median =
$$
Median(X) = {X_{\left[{{{n+1} \over 2}}\right]}}
$$

- When $n$ is even
\
\
    np.median =
$$
Median(X) = {1\over 2} \{{X_{\lfloor{{n+1\over 2}}\rfloor}}+X_{\lceil{{n+1\over 2}}\rceil}\}
$$

In [67]:
print("Median:", np.median(x))
print("Median along rows :", np.median(x, axis=0)) #np.median(x, 0)
print("Median along columns :", np.median(x, axis=1)) #np.median(x, 1)

Median: 0.38178157301378446
Median along rows : [0.36541321 0.31230602 0.69145852]
Median along columns : [0.28318842 0.16824088 0.38178157 0.69145852 0.36541321]


### np.sum()


In [68]:
print("Sum:", np.sum(x))
print("Sum along rows:", np.sum(x, axis=0)) #np.sum(x, 0)
print("Sum along columns :", np.sum(x, axis=1)) #np.sum(x, 1)

Sum: 7.095242902181846
Sum along rows: [1.84341172 2.24930634 3.00252484]
Sum along columns : [1.39459418 0.9221456  1.1779316  2.20089467 1.39967685]


### np.cov()


- Sample Covariance
$$
Cov(x,y) = S_{xy} = {1\over N-1} \sum^n_{i=1}{(X_i - \bar X)}{(Y_i - \bar Y)}
$$

$$
\begin{pmatrix} Cov(x,x) & Cov(x,y) \\ Cov(x,y) & Cov(y,y) \end{pmatrix}
$$

In [69]:
x = np.array([-2.1, -1,  4.3]) # N =3
y = np.array([3,  1.1,  0.12])

In [70]:
print("Covariance Matrix \n :", np.cov(x,y))
print("cov(x,y):",np.cov(x,y)[0][1])

Covariance Matrix 
 : [[11.71       -4.286     ]
 [-4.286       2.14413333]]
cov(x,y): -4.2860000000000005


In [71]:
np.var(x) # divides by N

7.806666666666666

In [72]:
np.cov(x,y)[0,0] #=var(x), #divides by N-1

11.709999999999999

In [73]:
np.var(x)*3/2

11.709999999999999

### Compute the mean, variance, and standard deviation of ( $\mathbf X$ : $N * 1$) as matrix operation

- Mean

$$\bar X = {1\over N} \sum^n_{i=1}X_i $$

$$
= {1\over N} \mathbf 1 \circ X = {1\over N} \mathbf 1^T  X
$$

$$
{1\over N} \begin{bmatrix} 1 &  \cdots &  1 \end{bmatrix}_{1*n} * \begin{bmatrix} X_1  \\ \vdots \\ X_n \end{bmatrix}_{n*1} = \bar X_{1*1}
$$

In [74]:
temp1 = np.random.rand(4,1) # X
temp1

array([[0.01791889],
       [0.123091  ],
       [0.44464703],
       [0.13126924]])

In [75]:
def MEAN_MADE(vector):
    N=vector.shape[0]  # can also do N=len(vector)
    return vector.T.dot(np.ones((N,1)))/N

In [77]:
print("Mean calculated from numpy:", np.mean(temp1))
print("Mean calculated from MEAN_MADE:", MEAN_MADE(temp1))

Mean calculated from numpy: 0.1792315389241266
Mean calculated from MEAN_MADE: [[0.17923154]]


In [78]:
MEAN_MADE(temp1).item()

0.1792315389241266

- Variance
    - VAR_MADE
$$
S^2 = {1\over N-1}{(X- \mathbf 1 \bar X)^T}{(X- \mathbf 1 \bar X)}
$$

In [79]:
temp1 # X

array([[0.01791889],
       [0.123091  ],
       [0.44464703],
       [0.13126924]])

In [80]:
def VAR_MADE(vector):
    mu = MEAN_MADE(vector).item()
    N = vector.shape[0]
    temp = vector - mu * np.ones((N,1))

    return temp.T.dot(temp)/(N-1)

In [87]:
print("Variance function in numpy:", np.var(temp1)*len(temp1)/(len(temp1)-1))
print("Variance from VAR_MADE:", VAR_MADE(temp1).item())

Variance function in numpy: 0.0339730998322364
Variance calculated from VAR_MADE: 0.0339730998322364


- Standard Deviation

$$Std(X) = \sqrt{Var(X)} = \sqrt{S^2} = S$$

In [89]:
def STD_MADE(vector):
    return np.sqrt(VAR_MADE(vector))

In [91]:
print("STD function in numpy:", np.std(temp1)*np.sqrt(len(temp1)/(len(temp1)-1)))
print("STD from STD_MADE:", STD_MADE(temp1).item())

STD function in numpy: 0.18431793139094307
STD from STD_MADE: 0.18431793139094307


- Covariance
    
$$
S_{xy} = {1\over N-1}∑{(X_i - \bar X)^T}{(Y_i - \bar Y)}
$$
- COVAR_MADE
$$
= {1\over N-1}{(X- \mathbf 1 \bar X)^T}{(Y- \mathbf 1 \bar Y)}
$$

In [92]:
def COVAR_MADE(vector1, vector2):
    mu1 = MEAN_MADE(vector1)[0,0]
    mu2 = MEAN_MADE(vector2)[0,0]
    N = len(vector1)

    temp1 = vector1 - mu1*np.ones((N,1))
    temp2 = vector2 - mu2*np.ones((N,1))

    return temp1.T.dot(temp2)/(N-1)

In [102]:
x = np.array([-2.1, -1,  4.3])
y = np.array([3,  1.1,  0.12])

In [101]:
print(np.cov(x,y))
print("Covariance of x and y from function in numpy:", np.cov(x,y)[0][1])

x=x.reshape((3,1))
y=y.reshape((3,1))

print("Covariance from COVAR_MADE:", COVAR_MADE(x,y).item())


[[11.71       -4.286     ]
 [-4.286       2.14413333]]
Covariance of x and y from function in numpy: -4.2860000000000005
Covariance from COVAR_MADE: -4.2860000000000005


In [123]:
##EXTRAS

- VAR_MADE2

$$
= {1\over N-1}{(\mathbf I X- {1\over N} \mathbf 1 \mathbf 1^T X)^T}{(\mathbf I X- {1\over N} \mathbf 1 \mathbf 1^T X)}
$$

$$
= {1\over N-1}{X^T(\mathbf I - {1\over N} \mathbf 1 \mathbf 1^T )^T}{(\mathbf I - {1\over N} \mathbf 1 \mathbf 1^T )X}
$$


In [106]:
def VAR_MADE2(vector):
    N = vector.shape[0]

    temp = np.eye(N)
    one_vec = np.ones((N,1))


    temp = temp - one_vec.dot(one_vec.T)/N

    return vector.T.dot(temp.T).dot(temp).dot(vector)/(N-1)

- VAR_MADE3
$$
= {1\over N-1}{X^T(\mathbf I - {1\over N} \mathbf 1 \mathbf 1^T )}X
$$

In [107]:
def VAR_MADE3(vector):
    N = vector.shape[0]

    temp = np.eye(N)
    one_vec = np.ones((N,1))

    temp = temp - one_vec.dot(one_vec.T)/N

    return vector.T.dot(temp).dot(vector)/(N-1)

In [108]:
print("Variance function in numpy:", np.var(temp1)*len(temp1)/(len(temp1)-1))
print("Variance calculated by made function1:", VAR_MADE(temp1))
print("Variance calculated by made function2:", VAR_MADE2(temp1))
print("Variance calculated by made function3:", VAR_MADE3(temp1))

Variance function in numpy: 0.0339730998322364
Variance calculated by made function1: [[0.0339731]]
Variance calculated by made function2: [[0.0339731]]
Variance calculated by made function3: [[0.0339731]]


In [109]:
VAR_MADE(temp1).item()

0.0339730998322364

In [110]:
VAR_MADE2(temp1).item()

0.03397309983223639

In [111]:
VAR_MADE3(temp1).item()

0.03397309983223639

- Standard Deviation

$$Std(X) = \sqrt{Var(X)} = \sqrt{S^2} = S$$

In [112]:
def STD_MADE(vector):
    return np.sqrt(VAR_MADE(vector))

In [113]:
print("Using function in numpy:", np.std(temp1)*np.sqrt(len(temp1)/(len(temp1)-1)))
print("Using STD_MADE:", STD_MADE(temp1))

Using function in numpy: 0.18431793139094307
Using STD_MADE: [[0.18431793]]


In [114]:
STD_MADE(temp1).item()

0.18431793139094307

- Covariance
    
$$
S_{xy} = {1\over N-1}∑{(X_i - \bar X)^T}{(Y_i - \bar Y)}
$$
- COVAR_MADE1
$$
= {1\over N-1}{(X- \mathbf 1 \bar X)^T}{(Y- \mathbf 1 \bar Y)}
$$
    
$$
= {1\over N-1}{(\mathbf I X- {1\over N} \mathbf 1 \mathbf 1^T X)^T}{(\mathbf I Y- {1\over N} \mathbf 1 \mathbf 1^T Y)}
$$
- COVAR_MADE2
$$
= {1\over N-1}{X^T(\mathbf I - {1\over N} \mathbf 1 \mathbf 1^T )^T}{(\mathbf I - {1\over N} \mathbf 1 \mathbf 1^T )Y}
$$
- COVAR_MADE3
$$
= {1\over N-1}{X^T(\mathbf I - {1\over N} \mathbf 1 \mathbf 1^T )}Y
$$

In [115]:
def COVAR_MADE(vector1, vector2):
    mu1 = MEAN_MADE(vector1)[0,0]
    mu2 = MEAN_MADE(vector2)[0,0]
    N = len(vector1)

    temp1 = vector1 - mu1*np.ones((N,1))
    temp2 = vector2 - mu2*np.ones((N,1))

    return temp1.T.dot(temp2)/(N-1)

In [116]:
def COVAR_MADE2(vector1, vector2):

    N = len(vector1)
    temp = np.eye(N)
    one_vec = np.ones((N,1))

    temp = temp - one_vec.dot(one_vec.T)/N

    return vector1.T.dot(temp.T).dot(temp).dot(vector2)/(N-1)

In [117]:
def COVAR_MADE3(vector1, vector2):
    N = len(vector1)

    temp = np.eye(N)
    one_vec = np.ones((N,1))

    temp = temp - one_vec.dot(one_vec.T)/N

    return vector1.T.dot(temp).dot(vector2)/(N-1)

In [118]:
x = np.array([-2.1, -1,  4.3])
y = np.array([3,  1.1,  0.12])

In [119]:
print(np.cov(x,y))
print("Covariance of x and y calculated by function in numpy:", np.cov(x,y)[0][1])

x=x.reshape((3,1))
y=y.reshape((3,1))

print("Covariance calculated by made function1:", COVAR_MADE(x,y))
print("Covariance calculated by made function2:", COVAR_MADE2(x,y))
print("Covariance calculated by made function3:", COVAR_MADE3(x,y))

[[11.71       -4.286     ]
 [-4.286       2.14413333]]
Covariance of x and y calculated by function in numpy: -4.2860000000000005
Covariance calculated by made function1: [[-4.286]]
Covariance calculated by made function2: [[-4.286]]
Covariance calculated by made function3: [[-4.286]]


In [120]:
COVAR_MADE(x,y).item()

-4.2860000000000005

In [121]:
COVAR_MADE2(x,y).item()

-4.286

In [122]:
COVAR_MADE3(x,y).item()

-4.286